{% set name = "openvscode-server" %}
{% set version = "1.81.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/gitpod-io/openvscode-server/archive/refs/tags/openvscode-server-v{{ version }}.tar.gz
  sha256: ee69ce529a0d0a9370503148617862612ea2db862f956ea7cc4d76e20db1b616
  folder: src
  patches:
    - 0001-Allow-running-on-subdir.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
    - sysroot_linux-64 2.17  # [build_platform == 'linux-64']
    - nodejs 16.*
    # We might need to ensure that we recompile all third-party deps to support OpenSSL 3+
    - openssl
    - jq
    - glib         # [linux]
    - libsecret    # [linux]
    - libxkbfile   # [linux]
    - xorg-libx11  # [linux]
  host:
    - nodejs 16.*
    # We might need to ensure that we recompile all third-party deps to support OpenSSL 3+
    - openssl
    - yarn <2
    - ripgrep
    - glib         # [linux]
    - libsecret    # [linux]
    - libxkbfile   # [linux]
    - xorg-libx11  # [linux]
  run:
    - nodejs 16.*
    - ripgrep

test:
  commands:
    - openvscode-server --help

about:
  home: https://github.com/gitpod-io/openvscode-server
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - ThirdPartyNotices.txt
  summary: Run upstream VS Code on a remote machine with access through a modern web browser from any device, anywhere.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
